# function for assigning hypothetical donors to collection volumes according to EBV, age, and/or donation history (agnostic to donation outcome)
vol_strat <- function(data, 
                      group,
                      vol, 
                      ebv_var 
){
  case_when(
            # single collection volume with age-based EBV deferral (current strategy)
            group == "current" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                           data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0), 
            # single volume with universal EBV-based deferral (strategy group 1V)
            group == "A.1" ~ case_when(data[[ebv_var]] >= (vol/1000 + 0.025)/0.15 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= (vol/1000 + 0.025)/0.15 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_LowHB", "Defer_Other") ~ 0,
                                       data[[ebv_var]] < (vol/1000 + 0.025)/0.15 ~ 0),
            group == "A.2" ~ case_when(data[[ebv_var]] >= (vol/1000 + 0.025)/0.13 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= (vol/1000 + 0.025)/0.13 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_LowHB", "Defer_Other") ~ 0,
                                       data[[ebv_var]] < (vol/1000 + 0.025)/0.13 ~ 0),
            # single volume with age-specific EBV-based deferral (strategy group 1Vʸ)
            group == "B.1" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[["agePulse"]] >= 26 ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[["agePulse"]] < 26 & data[[ebv_var]] >= (vol/1000 + 0.025)/0.15 ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[["agePulse"]] < 26 & data[[ebv_var]] < (vol/1000 + 0.025)/0.15 ~ 0),
            group == "B.2" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[["agePulse"]] >= 26 ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[["agePulse"]] < 26 & data[[ebv_var]] >= (vol/1000 + 0.025)/0.13 ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[["agePulse"]] < 26 & data[[ebv_var]] < (vol/1000 + 0.025)/0.13 ~ 0),
            # two volumes with universal EBV-based deferral (strategy group 2V)
            group == "C.1" ~ case_when(data[[ebv_var]] >= (vol/1000 + 0.025)/0.15 & data[[ebv_var]] < 0.500/0.15 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= (vol/1000 + 0.025)/0.15 & data[[ebv_var]] < 0.500/0.15 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < (vol/1000 + 0.025)/0.15 ~ 0,
                                       data[[ebv_var]] >= 0.500/0.15 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ 0.500/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.500/0.15 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0),
            group == "C.2" ~ case_when(data[[ebv_var]] >= (vol/1000 + 0.025)/0.13 & data[[ebv_var]] < 0.500/0.13 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= (vol/1000 + 0.025)/0.13 & data[[ebv_var]] < 0.500/0.13 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < (vol/1000 + 0.025)/0.13 ~ 0,
                                       data[[ebv_var]] >= 0.500/0.13 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ 0.500/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.500/0.13 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0),
            group == "C.3" ~ case_when(data[[ebv_var]] >= (vol/1000 + 0.025)/0.15 & data[[ebv_var]] < 0.520/0.15 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= (vol/1000 + 0.025)/0.15 & data[[ebv_var]] < 0.520/0.15 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < (vol/1000 + 0.025)/0.15 ~ 0,
                                       data[[ebv_var]] >= 0.520/0.15 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ 0.520/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.520/0.15 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0),
            group == "C.4" ~ case_when(data[[ebv_var]] >= (vol/1000 + 0.025)/0.13 & data[[ebv_var]] < 0.520/0.13 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ (vol/1000 + 0.025)/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= (vol/1000 + 0.025)/0.13 & data[[ebv_var]] < 0.520/0.13 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < (vol/1000 + 0.025)/0.13 ~ 0,
                                       data[[ebv_var]] >= 0.520/0.13 & data[["attendance_outcome"]] %in% c("Donate_Normal", "Donate_Under") ~ 0.520/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.520/0.13 & data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0),
            # three volumes with universal EBV-based deferral (strategy group 3V)
            group == "D.1" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.440/0.15 ~ 0,
                                       data[[ebv_var]] >= 0.440/0.15 & data[[ebv_var]] < 0.470/0.15 ~ 0.440/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.470/0.15 & data[[ebv_var]] < 0.500/0.15 ~ 0.470/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.500/0.15 ~ 0.500/data[[ebv_var]]*100),
            group == "D.2" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.440/0.13 ~ 0,
                                       data[[ebv_var]] >= 0.440/0.13 & data[[ebv_var]] < 0.470/0.13 ~ 0.440/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.470/0.13 & data[[ebv_var]] < 0.500/0.13 ~ 0.470/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.500/0.13 ~ 0.500/data[[ebv_var]]*100),
            group == "D.3" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.430/0.15 ~ 0,
                                       data[[ebv_var]] >= 0.430/0.15 & data[[ebv_var]] < 0.475/0.15 ~ 0.430/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.475/0.15 & data[[ebv_var]] < 0.520/0.15 ~ 0.475/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.520/0.15 ~ 0.520/data[[ebv_var]]*100),
            group == "D.4" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.430/0.13 ~ 0,
                                       data[[ebv_var]] >= 0.430/0.13 & data[[ebv_var]] < 0.475/0.13 ~ 0.430/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.475/0.13 & data[[ebv_var]] < 0.520/0.13 ~ 0.475/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.520/0.13 ~ 0.520/data[[ebv_var]]*100),
            # entirely personalised volumes (strategy group MV)
            group == "E.1" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.440/0.15 ~ 0,
                                       data[[ebv_var]] >= 0.440/0.15 & data[[ebv_var]] <= 0.500/0.15 ~ 15,
                                       data[[ebv_var]] > 0.500/0.15 ~ 0.500/data[[ebv_var]]*100),
            group == "E.2" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.440/0.13 ~ 0,
                                       data[[ebv_var]] >= 0.440/0.13 & data[[ebv_var]] <= 0.500/0.13 ~ 13,
                                       data[[ebv_var]] > 0.500/0.13 ~ 0.500/data[[ebv_var]]*100),
            group == "E.3" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.430/0.15 ~ 0,
                                       data[[ebv_var]] >= 0.430/0.15 & data[[ebv_var]] <= 0.520/0.15 ~ 15,
                                       data[[ebv_var]] > 0.520/0.15 ~ 0.520/data[[ebv_var]]*100),
            group == "E.4" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.430/0.13 ~ 0,
                                       data[[ebv_var]] >= 0.430/0.13 & data[[ebv_var]] <= 0.520/0.13 ~ 13,
                                       data[[ebv_var]] > 0.520/0.13 ~ 0.520/data[[ebv_var]]*100),

            # strategy allocating to multiple volumes based on EBV and donor history (strategy group MV+)
            group == "E.4_new" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[[ebv_var]] < 0.430/0.13 ~ 0,
                                       data[[ebv_var]] >= 0.430/0.13 & data[[ebv_var]] <= 0.520/0.13 & data[["new_donor"]] == 0 ~ 13,
                                       data[[ebv_var]] > 0.520/0.13 & data[["new_donor"]] == 0 ~ 0.520/data[[ebv_var]]*100,
                                       data[[ebv_var]] >= 0.430/0.13 & data[[ebv_var]] <= 0.520/0.13 & data[["new_donor"]] == 1 ~ 0.430/data[[ebv_var]]*100,
                                       data[[ebv_var]] > 0.520/0.13 & data[["new_donor"]] == 1 ~ 0.430/data[[ebv_var]]*100),
            # strategy allocating to multiple volumes based on both VVR history and EBV (replicate of E.4)
            group == "E.4_vvrhist" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                           data[[ebv_var]] < 0.430/0.13 ~ 0,
                                           data[[ebv_var]] >= 0.430/0.13 & data[[ebv_var]] <= 0.520/0.13 & data[["VVR_hist_bin"]] == 0 ~ 13,
                                           data[[ebv_var]] > 0.520/0.13 & data[["VVR_hist_bin"]] == 0 ~ 0.520/data[[ebv_var]]*100,
                                           data[[ebv_var]] >= 0.430/0.13 & data[[ebv_var]] <= 0.520/0.13 & data[["VVR_hist_bin"]] == 1 ~ 0.430/data[[ebv_var]]*100,
                                           data[[ebv_var]] > 0.520/0.13 & data[["VVR_hist_bin"]] == 1 ~ 0.430/data[[ebv_var]]*100),
            # strategies allocating to one of two volumes based on age only (strategy group 2Vʸ)
            group == "F.20.475" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[["agePulse"]] < 20 ~ 0.440/data[[ebv_var]]*100,
                                       data[["agePulse"]] >= 20 ~ 0.500/data[[ebv_var]]*100),
            group == "F.20.495" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                       data[["agePulse"]] < 20 ~ 0.430/data[[ebv_var]]*100,
                                       data[["agePulse"]] >= 20 ~ 0.520/data[[ebv_var]]*100),
            group == "F.26.475" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                            data[["agePulse"]] < 26 ~ 0.440/data[[ebv_var]]*100,
                                            data[["agePulse"]] >= 26 ~ 0.500/data[[ebv_var]]*100),
            group == "F.26.495" ~ case_when(data[["attendance_outcome"]] %in% c("Donate_None", "Defer_Other", "Defer_LowHB") ~ 0,
                                            data[["agePulse"]] < 26 ~ 0.430/data[[ebv_var]]*100,
                                            data[["agePulse"]] >= 26 ~ 0.520/data[[ebv_var]]*100),
            T ~ NA
            )
}
